// Save the skills list to a separate file
export const videoProductionSkills = [
  // Pre-Production
  "Concept Development",
  "Script Writing",
  "Screenwriting",
  "Storyboarding",
  "Shot List Creation",
  "Creative Direction",
  "Mood Boards",
  "Casting",
  "Location Scouting",
  "Production Planning",
  "Budgeting",
  "Scheduling",
  "Pre-visualization (Previs)",
  "Production Design",
  "Costume Design",
  "Prop Sourcing",
  "Lighting Setup Planning",

  // Production
  "Videography",
  "Cinematography",
  "Camera Operation",
  "Drone Videography",
  "Multi-Cam Setup",
  "Lighting Setup",
  "Sound Recording",
  "Boom Operation",
  "Green Screen Filming",
  "Live Streaming",
  "Event Filming",
  "Interview Filming",
  "Commercial Filming",
  "Music Video Filming",
  "Documentary Filming",

  // Post-Production
  "Adobe Premiere Pro",
  "Final Cut Pro",
  "DaVinci Resolve",
  "Avid Media Composer",
  "Sony Vegas Pro",
  "Adobe After Effects",
  "Motion Graphics",
  "2D Animation",
  "3D Animation",
  "Character Animation",
  "Explainer Videos",
  "Infographic Animation",
  "Color Correction",
  "Color Grading",
  "LUTs Application",
  "VFX (Visual Effects)",
  "CGI",
  "Rotoscoping",
  "Green Screen Keying",
  "Audio Editing",
  "Sound Design",
  "Foley",
  "Voiceover Editing",
  "ADR (Automated Dialogue Replacement)",
  "Mixing & Mastering",
  "Background Score",
  "Subtitling",
  "Closed Captioning",
  "Multi-language Subtitles",
  "Aspect Ratio Formatting",
  "Video Compression & Export",
  "YouTube Optimization",
  "Social Media Video Formatting",

  // Software Proficiency
  "Adobe Premiere Pro",
  "Adobe After Effects",
  "Adobe Audition",
  "Final Cut Pro",
  "DaVinci Resolve",
  "Avid Media Composer",
  "Blender",
  "Cinema 4D",
  "Maya",
  "3ds Max",
  "Pro Tools",
  "Logic Pro",
  "Audacity",

  // Project Types
  "Short Films",
  "Feature Films",
  "TV Commercials",
  "Corporate Videos",
  "Social Media Ads",
  "Wedding Films",
  "Event Coverage",
  "YouTube Content",
  "Podcasts",
  "VR/360° Video",
  "AR Video Content"
];